INSERT INTO subcategories
(category_id, subcategory_name, subcategory_description)
VALUES

(1,'Mobiles','Smartphones and accessories'),
(1,'Laptops','Laptops and notebooks'),
(1,'Tablets','Android and iPad tablets'),
(1,'Smart Watches','Wearable devices'),
(1,'Headphones','Audio accessories'),
(1,'Earbuds','Wireless earbuds'),
(1,'Speakers','Bluetooth and smart speakers'),
(1,'Cameras','DSLR and mirrorless cameras'),
(1,'Printers','Printers and scanners'),
(1,'Monitors','Computer monitors'),
(1,'Keyboards','Mechanical and wireless keyboards'),
(1,'Mouse','Gaming and office mouse'),
(1,'Gaming Consoles','PlayStation, Xbox and Nintendo'),
(1,'Computer Accessories','USB hubs, webcams, cables'),
(1,'Power Banks','Portable chargers'),
(1,'Storage Devices','SSD, HDD, Pen Drives'),
(1,'Networking','Routers and WiFi devices'),
(1,'Smart Home','Smart bulbs, cameras and sensors'),

(2,'Men''s Clothing','Clothing for men'),
(2,'Women''s Clothing','Clothing for women'),
(2,'Kids Clothing','Clothing for kids'),
(2,'Shoes','Footwear'),
(2,'Sports Shoes','Running and sports shoes'),
(2,'Sandals','Casual sandals'),
(2,'Bags','Handbags and backpacks'),
(2,'Wallets','Wallets and card holders'),
(2,'Watches','Fashion watches'),
(2,'Jewellery','Gold, silver and fashion jewellery'),
(2,'Sunglasses','Eyewear'),
(2,'Caps','Caps and hats'),
(2,'Belts','Leather and fabric belts'),
(2,'Ethnic Wear','Traditional clothing'),
(2,'Winter Wear','Jackets and sweaters'),

(3,'Furniture','Home furniture'),
(3,'Kitchen Appliances','Kitchen products'),
(3,'Home Decor','Decoration items'),
(3,'Cookware','Pans and cookware'),
(3,'Dinnerware','Plates and bowls'),
(3,'Storage & Containers','Kitchen storage'),
(3,'Cleaning Supplies','Cleaning products'),
(3,'Beds & Mattresses','Beds and mattresses'),
(3,'Lighting','LED lights and lamps'),
(3,'Curtains','Curtains and blinds'),
(3,'Bathroom Accessories','Bathroom essentials'),
(3,'Home Improvement','DIY tools'),

(4,'Education','Educational books'),
(4,'Fiction','Story books'),
(4,'Non-Fiction','Knowledge books'),
(4,'Comics','Comic books'),
(4,'Children Books','Books for kids'),
(4,'Competitive Exams','Exam preparation books'),
(4,'Programming','Coding books'),
(4,'Business','Business and finance'),
(4,'Biography','Life stories'),
(4,'Self Help','Self improvement'),

(5,'Cricket','Cricket equipment'),
(5,'Football','Football equipment'),
(5,'Badminton','Badminton equipment'),
(5,'Basketball','Basketball equipment'),
(5,'Volleyball','Volleyball equipment'),
(5,'Gym Equipment','Fitness products'),
(5,'Cycling','Bicycles and accessories'),
(5,'Yoga','Yoga mats and accessories'),
(5,'Swimming','Swimming gear'),
(5,'Outdoor Sports','Outdoor games'),

(6,'Makeup','Beauty makeup'),
(6,'Skin Care','Skin care products'),
(6,'Hair Care','Hair care products'),
(6,'Fragrances','Perfumes and deodorants'),
(6,'Men''s Grooming','Beard and shaving'),
(6,'Personal Care','Daily essentials'),
(6,'Nail Care','Nail polish and tools'),
(6,'Beauty Tools','Brushes and accessories'),

(7,'Educational Toys','Learning toys'),
(7,'Action Figures','Action figures'),
(7,'Remote Control Toys','RC cars and drones'),
(7,'Building Blocks','Construction toys'),
(7,'Board Games','Indoor games'),
(7,'Dolls','Dolls and accessories'),
(7,'Puzzles','Puzzle games'),
(7,'Outdoor Toys','Outdoor play equipment'),

(8,'Fruits & Vegetables','Fresh produce'),
(8,'Dairy Products','Milk, butter and cheese'),
(8,'Bakery','Bread and cakes'),
(8,'Snacks','Packaged snacks'),
(8,'Beverages','Drinks'),
(8,'Rice & Grains','Rice, wheat and cereals'),
(8,'Pulses','Dal and lentils'),
(8,'Cooking Oil','Edible oils'),
(8,'Spices','Indian spices'),
(8,'Tea & Coffee','Tea and coffee'),
(8,'Frozen Foods','Frozen products'),
(8,'Baby Food','Baby nutrition');